export const videoArray = [
  { id: 1, src: 'https://www.youtube.com/embed/Nzr023VwQRE', title: 'Avtomobil çəkilişi' },
  { id: 2, src: 'https://www.youtube.com/embed/UWn607f7i5A', title: 'Tədbir video' },
  { id: 3, src: 'https://www.youtube.com/embed/Av_IldNzEl8', title: 'Musiqi klipi' },
  { id: 4, src: 'https://www.youtube.com/embed/PfbM9nSniZI', title: 'Reklam layihəsi' },
  { id: 5, src: 'https://www.youtube.com/embed/qyiAUlGQFjs', title: 'Düğün çəkilişi' },
  { id: 6, src: 'https://www.youtube.com/embed/sKttIkQ9kdo', title: 'Korporativ video' },
  { id: 7, src: 'https://www.youtube.com/embed/iecJZNBwX2Q', title: 'Səyahət video' },
  { id: 8, src: 'https://www.youtube.com/embed/M_M9k8NPJ3k', title: 'Portfolio klipi' },
  { id: 9, src: 'https://www.youtube.com/embed/Kwame1QNjpc', title: 'Moda çəkilişi' },
  { id: 10, src: 'https://www.youtube.com/embed/7gCRhGEv6_U', title: 'Əyləncə video' },
  { id: 11, src: 'https://www.youtube.com/embed/G9NRzrx7m4U', title: 'Tədris video' },
  { id: 12, src: 'https://www.youtube.com/embed/nnz9wwfF3Fo', title: 'Film teaser' },
  { id: 13, src: 'https://www.youtube.com/embed/_1cBjvSsN00', title: 'Yaradıcı layihə' },
  { id: 14, src: 'https://www.youtube.com/embed/RXFZUZRGM3o', title: 'İdman çəkilişi' },
  { id: 15, src: 'https://www.youtube.com/embed/sOxloXyOAKA', title: 'Qısa film' },
  { id: 16, src: 'https://www.youtube.com/embed/2H_YyklnpFM', title: 'Brend storytelling' },
  { id: 17, src: 'https://www.youtube.com/embed/Gt3ViNwSOic', title: 'Müsahibə video' },
  { id: 18, src: 'https://www.youtube.com/embed/sWoQ_TuU1xI', title: 'Tədbir teaser' },
  { id: 19, src: 'https://www.youtube.com/embed/CSrvx22Ed2o', title: 'Yaradıcı content' },
  { id: 20, src: 'https://www.youtube.com/embed/qyiAUlGQFjs', title: 'Portfolio showcase' },
];
